In this project we will try to to

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as mp
import sqlite3

In [7]:
db_file = '/Users/Suha/Projects/TestGitHub/Chinook/chinook-database-master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite'
conn = sqlite3.connect(db_file)
q = "select * from sqlite_master"
cursor = conn.cursor()
a = cursor.execute(q).fetchall()

In [8]:
pd.read_sql_query(q,conn)

,type,name,tbl_name,rootpage,sql
0,table,Album,Album,2,CREATE TABLE [Album]\n(\n [AlbumId] INTEGER...
1,table,Artist,Artist,3,CREATE TABLE [Artist]\n(\n [ArtistId] INTEG...
2,table,Customer,Customer,4,CREATE TABLE [Customer]\n(\n [CustomerId] I...
3,table,Employee,Employee,7,CREATE TABLE [Employee]\n(\n [EmployeeId] I...
4,table,Genre,Genre,9,CREATE TABLE [Genre]\n(\n [GenreId] INTEGER...
5,table,Invoice,Invoice,10,CREATE TABLE [Invoice]\n(\n [InvoiceId] INT...
6,table,InvoiceLine,InvoiceLine,12,CREATE TABLE [InvoiceLine]\n(\n [InvoiceLin...
7,table,MediaType,MediaType,14,CREATE TABLE [MediaType]\n(\n [MediaTypeId]...
8,table,Playlist,Playlist,15,CREATE TABLE [Playlist]\n(\n [PlaylistId] I...
9,table,PlaylistTrack,PlaylistTrack,16,CREATE TABLE [PlaylistTrack]\n(\n [Playlist...
10,index,sqlite_autoindex_PlaylistTrack_1,PlaylistTrack,17,None
11,table,Track,Track,19,CREATE TABLE [Track]\n(\n [TrackId] INTEGER...
12,index,IPK_Album,Album,21,CREATE UNIQUE INDEX [IPK_Album] ON [Album]([Al...
13,index,IPK_Artist,Artist,22,CREATE UNIQUE INDEX [IPK_Artist] ON [Artist]([...
14,index,IPK_Customer,Customer,23,CREATE UNIQUE INDEX [IPK_Customer] ON [Custome...
15,index,IPK_Employee,Employee,24,CREATE UNIQUE INDEX [IPK_Employee] ON [Employe...
16,index,IPK_Genre,Genre,26,CREATE UNIQUE INDEX [IPK_Genre] ON [Genre]([Ge...
17,index,IPK_Invoice,Invoice,27,CREATE UNIQUE INDEX [IPK_Invoice] ON [Invoice]...
18,index,IPK_InvoiceLine,InvoiceLine,28,CREATE UNIQUE INDEX [IPK_InvoiceLine] ON [Invo...
19,index,IPK_MediaType,MediaType,29,CREATE UNIQUE INDEX [IPK_MediaType] ON [MediaT...
20,index,IPK_Playlist,Playlist,30,CREATE UNIQUE INDEX [IPK_Playlist] ON [Playlis...
21,index,IPK_PlaylistTrack,PlaylistTrack,31,CREATE UNIQUE INDEX [IPK_PlaylistTrack] ON [Pl...
22,index,IPK_Track,Track,32,CREATE UNIQUE INDEX [IPK_Track] ON [Track]([Tr...
23,index,IFK_AlbumArtistId,Album,33,CREATE INDEX [IFK_AlbumArtistId] ON [Album] ([...
24,index,IFK_CustomerSupportRepId,Customer,34,CREATE INDEX [IFK_CustomerSupportRepId] ON [Cu...
25,index,IFK_EmployeeReportsTo,Employee,36,CREATE INDEX [IFK_EmployeeReportsTo] ON [Emplo...
26,index,IFK_InvoiceCustomerId,Invoice,37,CREATE INDEX [IFK_InvoiceCustomerId] ON [Invoi...
27,index,IFK_InvoiceLineInvoiceId,InvoiceLine,38,CREATE INDEX [IFK_InvoiceLineInvoiceId] ON [In...
28,index,IFK_InvoiceLineTrackId,InvoiceLine,39,CREATE INDEX [IFK_InvoiceLineTrackId] ON [Invo...
29,index,IFK_PlaylistTrackTrackId,PlaylistTrack,40,CREATE INDEX [IFK_PlaylistTrackTrackId] ON [Pl...
30,index,IFK_TrackAlbumId,Track,41,CREATE INDEX [IFK_TrackAlbumId] ON [Track] ([A...
31,index,IFK_TrackGenreId,Track,42,CREATE INDEX [IFK_TrackGenreId] ON [Track] ([G...
32,index,IFK_TrackMediaTypeId,Track,43,CREATE INDEX [IFK_TrackMediaTypeId] ON [Track]...